local Extension = require("pi.ui.extension")

describe("subagent host select reply", function()
    it("encodes a table value and omits cancelled:false", function()
        local cmd = Extension._select_response("abc", { status = "completed" })
        assert.equals("extension_ui_response", cmd.type)
        assert.equals("abc", cmd.id)
        assert.is_nil(cmd.cancelled)
        local decoded = vim.json.decode(cmd.value)
        assert.equals("completed", decoded.status)
    end)

    it("falls back when the result cannot be encoded", function()
        local cmd = Extension._select_response("abc", { bad = function() end })
        assert.is_nil(cmd.cancelled)
        local decoded = vim.json.decode(cmd.value)
        assert.equals("failed to encode host result", decoded.error)
        assert.is_string(decoded.detail)
    end)

    it("sets cancelled only when the result is nil", function()
        local cmd = Extension._select_response("abc", nil)
        assert.is_true(cmd.cancelled)
        assert.is_nil(cmd.value)
    end)
end)
